# Generated by Django 4.2.3 on 2024-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="contact",
            field=models.CharField(default=9919278780, max_length=30),
            preserve_default=False,
        ),
    ]
