# Generated by Django 4.2.3 on 2024-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="/frontend/src/images/man.jpg", upload_to=""
            ),
        ),
    ]
