# Generated by Django 4.2.3 on 2024-06-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customuser_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=1000)),
                ("remark", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
