# Generated by Django 4.2.3 on 2024-06-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(default="media/man.jpg", upload_to=""),
        ),
    ]
