# Generated by Django 4.2.3 on 2024-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_petdetails_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petdetails",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
