# Generated by Django 4.2.3 on 2024-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_adoptiondetails_date_alter_petdetails_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petdetails",
            name="remark",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
