# Generated by Django 4.2.3 on 2024-06-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_petdetails_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(default="main road"),
            preserve_default=False,
        ),
    ]
