# Generated by Django 4.2.3 on 2024-06-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_customuser_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="petdetails",
            name="is_adopted",
            field=models.BooleanField(default=False),
        ),
    ]
