# Generated by Django 4.2.3 on 2024-06-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_customuser_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="contact",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
