# Generated by Django 4.2.3 on 2024-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_customuser_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser", name="address", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
