# Generated by Django 4.2.3 on 2024-06-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_adoptiondetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptiondetails",
            name="date",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="petdetails",
            name="date",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
